#! /bin/sh

# config 
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc config border_width         3
bspc config window_gap           12
bspc config top_padding          22
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# colorscheme
bspc config focused_border_color "#FFC1C6"
bspc config normal_border_color "#2E3440"

# autostart 
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/pictures/wallpapers/10-12.jpg
killall -q polybar
polybar example -q
